# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 16:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('blog', '0001_initial'), ('blog', '0002_section'), ('blog', '0003_auto_20171026_1702'), ('blog', '0004_auto_20171026_1702'), ('blog', '0005_section_name'), ('blog', '0006_remove_section_name')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('displayed_name', models.CharField(default=models.CharField(max_length=50), max_length=20)),
                ('url_name', models.CharField(default='section', max_length=50)),
            ],
        ),
    ]
