# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='name',
        ),
        migrations.AddField(
            model_name='section',
            name='displayed_name',
            field=models.CharField(default='section', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='url_name',
            field=models.CharField(default='section', max_length=50),
            preserve_default=False,
        ),
    ]
