# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171026_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='displayed_name',
            field=models.CharField(default=models.CharField(max_length=50), max_length=20),
        ),
    ]
