# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20171026_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='name',
            field=models.CharField(default='section', max_length=50),
        ),
    ]
