# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 15:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_section_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='name',
        ),
    ]
